// ============================================================
// Protocol App — Core Type Definitions
// ============================================================

/** A single daily habit within a protocol */
export interface Habit {
  id: string;
  title: string;
  description: string;
  frequency: 'daily' | 'weekly' | 'biweekly' | 'monthly';
  /** How many times per frequency period */
  timesPerPeriod: number;
  category: 'nutrition' | 'training' | 'recovery' | 'mindset' | 'skill' | 'other';
  /** Optional unit of measure (e.g., "grams", "minutes", "reps") */
  unit?: string;
  /** Optional target value (e.g., 160 for "160g protein") */
  targetValue?: number;
}

/** A weekly or monthly milestone checkpoint */
export interface Milestone {
  id: string;
  title: string;
  description: string;
  targetDate: string; // ISO date string
  completed: boolean;
  /** Numeric target for progress tracking */
  targetValue?: number;
  currentValue?: number;
  unit?: string;
}

/** The full protocol generated by the AI */
export interface Protocol {
  id: string;
  goalTitle: string;
  goalDescription: string;
  timeframe: string; // e.g., "12 months", "6 months"
  createdAt: string; // ISO date string
  habits: Habit[];
  milestones: Milestone[];
  /** Raw AI-generated summary/rationale */
  summary: string;
}

/** A single day's check-in record */
export interface DailyCheckIn {
  date: string; // ISO date string (YYYY-MM-DD)
  habitCompletions: Record<string, boolean>; // habitId -> completed
  notes?: string;
}

/** Aggregated adherence data for charts */
export interface AdherenceDataPoint {
  date: string;
  adherenceRate: number; // 0-100
  habitsCompleted: number;
  habitsTotal: number;
}

/** Correlation data point for habit vs outcome chart */
export interface CorrelationDataPoint {
  week: string;
  adherenceRate: number;
  progressMetric: number;
  label?: string;
}

/** User profile and app state */
export interface UserProfile {
  onboardingComplete: boolean;
  subscribed: boolean;
  protocol: Protocol | null;
  checkIns: DailyCheckIn[];
  createdAt: string;
}

/** Chat message in the onboarding flow */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

/** Onboarding session state */
export interface OnboardingSession {
  messages: ChatMessage[];
  goalDraft: string;
  phase: 'goal-input' | 'screening' | 'generating' | 'complete';
}
